### ISSUE TITLE
Pickle issue on restoring mock script

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1038]
Modified the files in tests/unit/pywbemcli/testmock to create the script definition for py3 and py2.  The result fails when trying to restore the pickle after saving the installed script.

It fails with the exception:

_pickle.PicklingError: Can't pickle <class 'unittest.mock.Mock'>: it's not the same object as unittest.mock.Mock.  The full traceback is in the following comment.

I will install the new script as its own branch this morning to continue testing.

Stack comments indicate that this is a known issue and sometimes occurs when the same thing is imported in multiple ways in different parts of the environment (ex. import x vs from x import y)

The issue may come from some changes I made in using this mock for the test of the subscription command.

**Comment by KSchopmeyer** [comment]
Traceback from failure


```
Traceback (most recent call last):
  File "/home/kschopmeyer/virtualenvs/pycli39/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/pywbemcli.py", line 894, in cli
    ctx.invoke(repl)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/pywbemcli.py", line 972, in repl
    click_repl.repl(ctx, prompt_kwargs=prompt_kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click_repl/__init__.py", line 259, in repl
    group.invoke(ctx)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_cmd_class.py", line 149, in class_enumerate
    context.execute_cmd(lambda: cmd_class_enumerate(context, classname,
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 347, in execute_cmd
    cmd()  # The pywbemcli command function call.
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_cmd_class.py", line 149, in <lambda>
    context.execute_cmd(lambda: cmd_class_enumerate(context, classname,
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_cmd_class.py", line 898, in cmd_class_enumerate
    results = enumerate_classes_filtered(context, classname, options)
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_cmd_class.py", line 778, in enumerate_classes_filtered
    conn = context.pywbem_server.conn
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_pywbem_server.py", line 391, in conn
    return self.wbem_server.conn
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_pywbem_server.py", line 412, in wbem_server
    self.connect(
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_pywbem_server.py", line 551, in connect
    conn.build_mockenv(
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_pywbemcli_operations.py", line 504, in build_mockenv
    self._dump_mockenv(mockenv_pickle_file)
  File "/home/kschopmeyer/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli/_pywbemcli_operations.py", line 608, in _dump_mockenv
    pickle.dump(mockenv, fp)
_pickle.PicklingError: Can't pickle <class 'unittest.mock.Mock'>: it's not the same object as unittest.mock.Mock

**Comment by KSchopmeyer** [comment]
Close as local issue

**Comment by andy-maier** [comment]
pywbemtools 1.0.0 is supposed to require pywbem 1.3.0, so I set the milestone for this issue to 1.0.0.
