### ISSUE TITLE
pywbemcli does not work on the WBEM Server Profile

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#1075]
THIS ISSUE IS A LOW PRIORITY
Three command groups of the pywbemcli do not work on the DMTF WBEM Server profile.  The command groups are:
Namespace - Fails because only looking for CIM_Namespace (and not CIM_WBEMServerNamespace)
Server - Fails because only looking for CIM_Namespace (and not CIM_WBEMServerNamespace)
Subscription - Fails because there is no CIM_ObjectManager class in the interop namespace
Fixing Namespace and Server should be pretty easy. The error message was: "Error: ModelError: Namespace class could not be determined (tried ['CIM_Namespace', '__Namespace'])". What is needed is trying 'CIM_WBEMServerNamespace' as well as the two listed in the message.
Fixing the CIM_ObjectManager may be a little more complicated. I get the error on both the list and add commands.

**Comment by FarmerMike252** [comment]
The error message I get for the subscription commands is; "CIMError: 5 (CIM_ERR_INVALID_CLASS): Class 'CIM_ObjectManager' not found in namespace 'interop'." The DMTF WBEM Server Profile does not contain the class CIM_ObjectManager. It is not obvious why the subscription routines needs the CIM_ObjectManager. It might be to find the CIM_ObjectManagerCommunicationMechanism. If that is what it is, then find the instance of CIM_WBEMServer, then follow the CIM_ServiceServiceDependency to the CIM_ProtocolService. The CIM_ProtocolService has a "Protocol" property.

**Comment by FarmerMike252** [comment]
A trace of CIM_ObjectManager error is:
pywbemcli> subscription list-filters
Traceback (most recent call last):
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem_mock\_baseprovider.py", line 417, in get_class
    klass = class_store.get(classname, copy=True)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem_mock\_inmemoryrepository.py", line 106, in get
    raise KeyError('Name {} not in {} object store'
KeyError: "Name CIM_ObjectManager not in <class 'pywbem._cim_obj.CIMClass'> object store"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem_mock\_mainprovider.py", line 1583, in EnumerateInstances
    cl = self.get_class(namespace, ClassName, local_only=False)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem_mock\_baseprovider.py", line 419, in get_class
    raise CIMError(
pywbem._exceptions.CIMError: 6 (CIM_ERR_NOT_FOUND): Class 'CIM_ObjectManager' not found in namespace 'interop'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\FarmerMike\Envs\subscription\Scripts\pywbemcli-script.py", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\farmermike\devenv2\subscriptions\pywbemtools\pywbemtools\pywbemcli\pywbemcli.py", line 992, in cli
    ctx.invoke(repl)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\farmermike\devenv2\subscriptions\pywbemtools\pywbemtools\pywbemcli\pywbemcli.py", line 1070, in repl
    click_repl.repl(ctx, prompt_kwargs=prompt_kwargs)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click_repl\__init__.py", line 259, in repl
    group.invoke(ctx)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\farmermike\devenv2\subscriptions\pywbemtools\pywbemtools\pywbemcli\_cmd_subscription.py", line 370, in subscription_list_filters
    context.execute_cmd(lambda: cmd_subscription_list_filters(context, options))
  File "c:\users\farmermike\devenv2\subscriptions\pywbemtools\pywbemtools\pywbemcli\_context_obj.py", line 319, in execute_cmd
    cmd()  # The pywbemcli command function call.
  File "c:\users\farmermike\devenv2\subscriptions\pywbemtools\pywbemtools\pywbemcli\_cmd_subscription.py", line 370, in <lambda>
    context.execute_cmd(lambda: cmd_subscription_list_filters(context, options))
  File "c:\users\farmermike\devenv2\subscriptions\pywbemtools\pywbemtools\pywbemcli\_cmd_subscription.py", line 1653, in cmd_subscription_list_filters
    csm = CmdSubscriptionManager(context, options)
  File "c:\users\farmermike\devenv2\subscriptions\pywbemtools\pywbemtools\pywbemcli\_cmd_subscription.py", line 606, in __init__
    self._server_id = self._submgr.add_server(
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem\_subscription_manager.py", line 382, in add_server
    self._systemnames[server_id] = server.cimom_inst['SystemName']
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem\_server.py", line 364, in cimom_inst
    self._determine_brand()
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem\_server.py", line 1227, in _determine_brand
    cimom_insts = self._conn.EnumerateInstances(
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem\_cim_operations.py", line 3011, in EnumerateInstances
    result = self._imethodcall(
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem_mock\_wbemconnection_mock.py", line 1226, in _mock_imethodcall
    result = methodnameattr(namespace, **params)
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem_mock\_wbemconnection_mock.py", line 1400, in _imeth_EnumerateInstances
    instances = self._mainprovider.EnumerateInstances(
  File "C:\Users\FarmerMike\Envs\subscription\lib\site-packages\pywbem_mock\_mainprovider.py", line 1586, in EnumerateInstances
    raise CIMError(
pywbem._exceptions.CIMError: 5 (CIM_ERR_INVALID_CLASS): Class 'CIM_ObjectManager' not found in namespace 'interop'.

**Comment by FarmerMike252** [comment]
I marked this as a low priority, since SMI-S requires the deprecated SNIA server profile be implemented (to support infrastructures such as Pegasus that have not yet implemented the DMTF WBEM Server profile).

**Comment by andy-maier** [comment]
I'm afraid I have to say that I think it is a bad idea to use the WBEM Server Profile in SMI-S. SMI-S will not be able to get rid of CIM_Namespace/CIM_ObjectManager because doing so would be incompatible for any SMI-S client. If they need to stay, what exactly is the purpose of adding a new incompatible profile that just covers this same area in different ways?

Note that these classes are needed very early in the game. Without understanding what the name of the Interop namespace is, a client cannot even discover profiles. The pywbem WBEMServer class determines that today by using the CIM_Namespace / CIM_ObjectManager classes. Maybe it could do that without relying on these clases, or by also tolerating an alternative implementation of only the WBEM Server Profile, but why should it, when these classes in all likelihood will continue to be provided for a long time for compatibility reasons.

**Comment by KSchopmeyer** [comment]
Action: get agreement on what Mike is implementing and clarify and document what is needed for close of this profile.

**Comment by KSchopmeyer** [comment]
Karl: Finish dicsussion with Mike to determine what requirements this will put on pywbem.  As far as we can tell, the only real issue today would be for the use of the new class for namespace defined for the WBEM server profile so that are change would be to try both classes when we find namespaces.

ACTION: Karl, discuss with Mike

**Comment by andy-maier** [comment]
I opened https://github.com/pywbem/pywbem/issues/2845 for adding support for the new namespace class in pywbem.

Mike, in the mean time you can do in the mock environment what a real world implementation would also do: Have support for both the existing namespace representation with CIM_Namespace, and for the new one introduced by the WBEM Server Profile.

**Comment by KSchopmeyer** [comment]
We agreed that pywbem does want to support the WBEMServer profile class used for namespace management but nothing else in the WBEM profile.

**Comment by KSchopmeyer** [comment]
We agree that the task for us is to implement the CIM_WBEMNamespace class as a provieder in PYWBEM per the issue above.

**Comment by KSchopmeyer** [comment]
Closed. Will proceed with other issues
