### ISSUE TITLE
Resolve hang in "make test" on Python 2.7

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#1327]
Since we switched over to the container based Python 2.7 environment, the test_list_cmd.py unit test for pywbemlistener seems to hang for a long time, before the action step is automatically cancelled.

First weekly test run with that issue: https://github.com/pywbem/pywbemtools/actions/runs/5703317982/job/15455850462

Last weekly test before the switch, that succeeded: https://github.com/pywbem/pywbemtools/actions/runs/5232731273

On a locally installed Python 2.7 on macOS (Andy) or Ubuntu (Karl), the issue cannot be reproduced. It probably requires setting up the same container based Python 2.7 as in the Actions runs to reproduce it.

**Comment by KSchopmeyer** [comment]
More news.  Tested running in python:2..7.8-buster container locally and no problem.tests/unit/pywbemlistener/test_list_cmd.py .....
tests/unit/pywbemlistener/test_run_cmd.py .....
tests/unit/pywbemlistener/test_show_cmd.py ....
tests/unit/pywbemlistener/test_start_cmd.py .....................
tests/unit/pywbemlistener/test_stop_cmd.py ....
tests/unit/pywbemlistener/test_tabcompletion_unit.py ...
tests/unit/pywbemlistener/test_test_cmd.py .......

======================================================== warnings summary ========================================================
pywbemtools/_output_formatting.py:36
  /pywbemtools/pywbemtools/pywbemtools/_output_formatting.py:36: DeprecationWarning: Pywbem support for Python 2.7 is deprecated and will be removed in a future version
    from pywbem import CIMInstanceName

tests/unit/pywbemcli/test_common.py:705
  /pywbemtools/pywbemtools/tests/unit/pywbemcli/test_common.py:705: DeprecationWarning: The propagation of key property values of pywbem.CIMInstance to its path keybindings is deprecated and will be removed in a future version of pywbem
    path=CIMInstanceName('CIM_Foo', {'Name': 'Foo'})),

-- Docs: https://docs.pytest.org/en/latest/warnings.html

---------- coverage: platform linux2, python 2.7.18-final-0 ----------
Name                                              Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------
pywbemtools/__init__.py                               8      2    75%   27, 29
pywbemtools/_click_extensions.py                     90      4    96%   132-133, 316-319
pywbemtools/_common_cmd_actions.py                   33      4    88%   38-41
pywbemtools/_options.py                              13      0   100%
pywbemtools/_output_formatting.py                   169     16    91%   29-30, 115, 142, 227, 293-294, 342-344, 408, 415, 418, 422, 428, 504
pywbemtools/_utils.py                                58      4    93%   170-173
pywbemtools/_version.py                               2      0   100%
pywbemtools/pywbemcli/__init__.py                    31      0   100%
pywbemtools/pywbemcli/_association_shrub.py         248      7    97%   59, 160, 468, 580, 715-717, 832
pywbemtools/pywbemcli/_cimvalueformatter.py         125      8    94%   43, 174-178, 200-204, 448
pywbemtools/pywbemcli/_cmd_class.py                 278     13    95%   764-777, 803, 935-936, 943-944
pywbemtools/pywbemcli/_cmd_connection.py            319     22    93%   493, 527, 604-614, 645, 729-734, 746, 750, 802, 846, 857-860, 974
pywbemtools/pywbemcli/_cmd_docs.py                   11      1    91%   45
pywbemtools/pywbemcli/_cmd_help.py                   20      2    90%   46-48
pywbemtools/pywbemcli/_cmd_instance.py              508     24    95%   931, 949, 1123-1124, 1252, 1343, 1483-1485, 1493-1509, 1538, 1560, 1592-1593
pywbemtools/pywbemcli/_cmd_namespace.py             124     14    89%   205, 254-255, 278-279, 288, 292-293, 302-303, 317-318, 328-329
pywbemtools/pywbemcli/_cmd_profile.py               102      7    93%   179-180, 264-265, 285-288
pywbemtools/pywbemcli/_cmd_qualifier.py              69      3    96%   176-177, 198
pywbemtools/pywbemcli/_cmd_server.py                237      6    97%   328-329, 398-399, 420, 468
pywbemtools/pywbemcli/_cmd_statistics.py            190     29    85%   236, 242-247, 286-287, 292-294, 302-303, 310, 364-365, 367, 437-438, 468-471, 474, 478, 503-504, 507, 513, 529, 596-597
pywbemtools/pywbemcli/_cmd_subscription.py          683     47    93%   625, 628, 710-711, 740-741, 766-767, 839-842, 859-864, 908-909, 923-924, 1180-1191, 1246-1252, 1256-1257, 1455, 1504, 1553, 1727, 1801, 1846, 1858, 1869-1870, 1887, 1900, 2066, 2091-2092
pywbemtools/pywbemcli/_common.py                    535     44    92%   53, 89, 219, 254, 259, 279-280, 349, 351, 366, 375-376, 433-434, 522, 528-529, 534, 587, 599, 608, 612-625, 650-651, 656, 670, 825, 827, 948, 953, 970, 1262, 1470-1471, 1515-1516
pywbemtools/pywbemcli/_common_cmd_functions.py      222     14    94%   125, 131, 232-235, 295, 320-324, 598-599, 631
pywbemtools/pywbemcli/_common_options.py             14      0   100%
pywbemtools/pywbemcli/_connection_repository.py     171      1    99%   137
pywbemtools/pywbemcli/_context_obj.py               127     28    78%   103, 220, 243-246, 254, 304-310, 316-317, 392-398, 410-426
pywbemtools/pywbemcli/_display_cimobjects.py        432     49    89%   174-177, 211, 232, 254, 264, 337, 383, 395, 439, 448, 457-468, 474-475, 481-485, 502, 525, 532, 563-567, 597-598, 617-620, 623-625, 683-684, 702, 957-962, 987, 989
pywbemtools/pywbemcli/_displaytree.py                80      0   100%
pywbemtools/pywbemcli/_pywbem_server.py             259     31    88%   46, 68, 77, 179, 182, 201, 218, 234, 250, 269, 292, 313, 327, 345, 362, 380, 443, 564, 613, 634-635, 638, 641, 652, 690-692, 698, 705, 709, 721
pywbemtools/pywbemcli/_pywbemcli_operations.py      183     41    78%   293, 379, 437, 450-452, 463-471, 511-529, 569-573, 633-655, 686-687, 735-738
pywbemtools/pywbemcli/_warnings.py                    6      0   100%
pywbemtools/pywbemcli/config.py                      28      0   100%
pywbemtools/pywbemcli/mockscripts/__init__.py        81     31    62%   104-126, 139-140, 182-208, 218
pywbemtools/pywbemcli/pywbemcli.py                  331     30    91%   119-120, 130-131, 158-182, 214-218, 249, 253, 305, 309, 815, 869, 920, 969, 1020, 1025, 1041, 1067
pywbemtools/pywbemlistener/__init__.py               11      0   100%
pywbemtools/pywbemlistener/_cmd_docs.py              11      1    91%   45
pywbemtools/pywbemlistener/_cmd_help.py              18      2    89%   45-47
pywbemtools/pywbemlistener/_cmd_listener.py         517     60    88%   64-67, 165-172, 296, 503, 510-513, 614, 623, 641-644, 647-654, 687-696, 709-726, 843, 998, 1016, 1079-1087, 1092, 1111-1112, 1213, 1225-1226, 1250, 1253, 1331-1333, 1341-1342
pywbemtools/pywbemlistener/_config.py                10      0   100%
pywbemtools/pywbemlistener/_context_obj.py           53      7    87%   69, 133-136, 143, 168-169
pywbemtools/pywbemlistener/pywbemlistener.py         32      0   100%
-------------------------------------------------------------------------------
TOTAL                                              6439    552    91%

===================================== 1584 passed, 30 skipped

So it is apparently not just running the tests in the container but something  more in how I am running the tests locally vs how run in github CI test.  Going to dig further.

**Comment by KSchopmeyer** [comment]
Certainly not a multi hour loop.

**Comment by KSchopmeyer** [comment]
KS: Set up a simple buster container test (start python:2.7.18-buster container, clone pywbemtools into container and run install and tests.  Did not fail.  The Docker container must be doing something more to fail.

**Comment by KSchopmeyer** [comment]
docker run -it --rm python:2.7.18-buster

in the container:

git clone ...

make build
make check
make pylint
make builddoc
make test

**Comment by KSchopmeyer** [comment]
NOTE: There exists a tool (act) that allows running github workflows in a local system.  

https://medium.com/@debasishkumardas5/running-github-actions-locally-a-complete-guide-for-windows-mac-and-linux-users-34c45999c7cd

However still working to get it running correctly with pywbemtools

**Comment by KSchopmeyer** [comment]
We concluded that the problem is clearly with the python 2.7 subprocess library and the python:2.7.18buster container  when running github CI.

IT does not occur when "make test" is run in the python 2.7.1Buster container locally. 

Karl found  a substitute library for python 2.7 suprocess (subprocess32 backported to pythn 2.7).  It is actually recommended in the pythond 2.7 documentation as an alternate https://docs.python.org/2/library/subprocess.html. It is available on Pypi https://pypi.org/project/subprocess32/ and implementes the comunicate() timeout parameter. This helps us because: 

1. I means we do not have to have a separate path for python 2.7 in the pywbemlistener tests common code.
2. It allows us to actually see what is happening when p.communicate() does not return. Without this we get a complete test failure and no data.  With this the test stops on the timeout and any data we captured in logs from pywbemlistener can be recovered.
3. It passes all the other local tests and tests in the local buster container.

However, it does not stop the p.communicate(...) from getting into a loop in the pywbemlistener tests that involve pywbelistener stop as part of the github CI tests.

**Comment by KSchopmeyer** [comment]
We implemented a number of debug displays in pywbemlistener using the debug_log function to attempt to find out where the communicate was getting into a loop.  The following is one result from this set of modifications and is in the PR https://github.com/pywbem/pywbemtools/pull/1333.

'Here is an output of the test_list_cmd.py which is the only one that runs.  I have commented some of the things I found

```Here
2023-09-29T17:24:41.0391470Z ##[group]Run make test
2023-09-29T17:24:41.0391703Z [36;1mmake test[0m
2023-09-29T17:24:41.0391970Z shell: sh -e {0}
2023-09-29T17:24:41.0392152Z env:
2023-09-29T17:24:41.0392401Z   TEST_SERVER_IMAGE: kschopmeyer/openpegasus-server:0.1.1
2023-09-29T17:24:41.0392753Z   TEST_SERVER_IMAGE_TAR: openpegasus-server:0.1.1.tar.gz
2023-09-29T17:24:41.0393095Z   DOCKER_CACHE_DIR: ~/docker-cache
2023-09-29T17:24:41.0393328Z   PIP_DISABLE_PIP_VERSION_CHECK: 1
2023-09-29T17:24:41.0393571Z   PIP_NO_PYTHON_VERSION_WARNING: 1
2023-09-29T17:24:41.0393800Z   PACKAGE_LEVEL: latest
2023-09-29T17:24:41.0393999Z   TESTOPTS: -vv
2023-09-29T17:24:41.0394212Z   TESTCASES: test_list_cmd.py
2023-09-29T17:24:41.0394422Z ##[endgroup]
2023-09-29T17:24:43.0442174Z Makefile: Running unit and function tests
2023-09-29T17:24:43.0443270Z PYWBEMTOOLS_TERMWIDTH=120 py.test --color=yes --cov pywbemtools  --cov-config .coveragerc -W default -W ignore::PendingDeprecationWarning -vv -k test_list_cmd.py tests/unit -s
2023-09-29T17:24:43.3685706Z [1m============================= test session starts ==============================[0m
2023-09-29T17:24:43.3686254Z platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.11.0, pluggy-0.13.1 -- /usr/local/bin/python
2023-09-29T17:24:43.3802227Z cachedir: .pytest_cache
2023-09-29T17:24:43.3802517Z rootdir: /__w/pywbemtools/pywbemtools
2023-09-29T17:24:43.3802856Z plugins: cov-2.12.1
2023-09-29T17:24:45.0725092Z [1mcollecting ... [0mcollected 1619 items / 1614 deselected / 5 selected
2023-09-29T17:24:45.0734345Z
2023-09-29T17:24:47.5448703Z tests/unit/pywbemlistener/test_list_cmd.py::test_lis_list[Verify output of 'list --help'-inputs0-exp_results0-True] [32mPASSED[0m
2023-09-29T17:24:50.0000092Z tests/unit/pywbemlistener/test_list_cmd.py::test_lis_list[Verify output of 'list -h'-inputs1-exp_results1-True] [32mPASSED[0m
2023-09-29T17:24:50.0013397Z tests/unit/pywbemlistener/test_list_cmd.py::test_lis_list[Verify output of 'list' with no listener running-inputs2-exp_results2-verbose]
2023-09-29T17:24:50.0013978Z Executing testcase: Verify output of 'list' with no listener running
2023-09-29T17:24:50.0014464Z test setup: Listing listeners: pywbemlistener -o plain list
2023-09-29T17:24:50.0014872Z test setup: Command (shell): pywbemlistener -o plain list
2023-09-29T17:24:50.0039126Z Debug: test setup: Calling p.communicate
2023-09-29T17:24:50.8188604Z Debug: test setup: Returned from p.communicate() with 21 B on out, None B on stderr
2023-09-29T17:24:50.8188984Z Debug: test setup: Calling p.poll()
2023-09-29T17:24:50.8189266Z Debug: test setup: Returned from p.poll() with rc=0
2023-09-29T17:24:50.8189447Z
2023-09-29T17:24:50.8189566Z Environment: PYWBEMTOOLS_TERMWIDTH=120
2023-09-29T17:24:50.8189864Z Command (shell): pywbemlistener list >out.log 2>err.log
2023-09-29T17:24:51.6363589Z Exit code: 0
2023-09-29T17:24:51.6364098Z Stdout: 'No running listeners\n'
2023-09-29T17:24:51.6364338Z Stderr: ''
2023-09-29T17:24:51.6364703Z test teardown: Listing listeners: pywbemlistener -o plain list
2023-09-29T17:24:51.6365123Z test teardown: Command (shell): pywbemlistener -o plain list
2023-09-29T17:24:51.6389968Z Debug: test teardown: Calling p.communicate
2023-09-29T17:24:52.4519294Z Debug: test teardown: Returned from p.communicate() with 21 B on out, None B on stderr
2023-09-29T17:24:52.4520339Z Debug: test teardown: Calling p.poll()
2023-09-29T17:24:52.4521072Z Debug: test teardown: Returned from p.poll() with rc=0
2023-09-29T17:24:52.4550739Z [32mPASSED[0m
2023-09-29T17:24:52.4566127Z tests/unit/pywbemlistener/test_list_cmd.py::test_lis_list[Verify output of 'list' with one http listener running-inputs3-exp_results3-verbose]
2023-09-29T17:24:52.4566693Z Executing testcase: Verify output of 'list' with one http listener running
2023-09-29T17:24:52.4567126Z test setup: Listing listeners: pywbemlistener -o plain list
2023-09-29T17:24:52.4567513Z test setup: Command (shell): pywbemlistener -o plain list
2023-09-29T17:24:52.4591200Z Debug: test setup: Calling p.communicate
2023-09-29T17:24:53.2756372Z Debug: test setup: Returned from p.communicate() with 21 B on out, None B on stderr
2023-09-29T17:24:53.2756765Z Debug: test setup: Calling p.poll()
2023-09-29T17:24:53.2757042Z Debug: test setup: Returned from p.poll() with rc=0
2023-09-29T17:24:53.2757671Z test setup: Starting listener: pywbemlistener -vv start lis1 --scheme http --port 50001
2023-09-29T17:24:53.2758188Z test setup: Command (shell): pywbemlistener -vv start lis1 --scheme http --port 50001
2023-09-29T17:24:53.2784947Z Debug: test setup: Calling p.communicate
2023-09-29T17:24:54.9058946Z Debug: test setup: Returned from p.communicate() with 365 B on out, None B on stderr
2023-09-29T17:24:54.9059327Z Debug: test setup: Calling p.poll()
2023-09-29T17:24:54.9059613Z Debug: test setup: Returned from p.poll() with rc=0
2023-09-29T17:24:54.9067784Z
2023-09-29T17:24:54.9068070Z Environment: PYWBEMTOOLS_TERMWIDTH=120
2023-09-29T17:24:54.9068693Z Command (shell): pywbemlistener -o plain list >out.log 2>err.log
2023-09-29T17:24:55.7324013Z Exit code: 0
2023-09-29T17:24:55.7326338Z Stdout: 'Name      Port  Scheme    Bind addr      PID  Created\n
                                      lis1     50001  http      none          1298  2023-09-29 17:24:53\n'
2023-09-29T17:24:55.7326686Z Stderr: ''
2023-09-29T17:24:55.7327033Z test teardown: Listing listeners: pywbemlistener -o plain list
2023-09-29T17:24:55.7330832Z test teardown: Command (shell): pywbemlistener -o plain list
2023-09-29T17:24:55.7368094Z Debug: test teardown: Calling p.communicate
2023-09-29T17:24:56.5543201Z Debug: test teardown: Returned from p.communicate() with 120 B on out, None B on stderr
2023-09-29T17:24:56.5543939Z Debug: test teardown: Calling p.poll()
2023-09-29T17:24:56.5544695Z Debug: test teardown: Returned from p.poll() with rc=0
2023-09-29T17:24:56.5545070Z test teardown: Stopping listener: pywbemlistener stop lis1
2023-09-29T17:24:56.5545404Z test teardown: Command (shell): pywbemlistener stop lis1
2023-09-29T17:24:56.5576546Z Debug: test teardown: Calling p.communicate
2023-09-29T17:25:26.5580121Z Debug: test teardown: p.communicate() raised TimeoutExpired: Command 'pywbemlistener stop lis1' timed out after 30 seconds
================p.communicate in teardown with pywbemlistener causes timeout.
2023-09-29T17:25:26.5600063Z [
u"2023-09-29 17:24:17 cli: CLI call info_name=u'pywbemlistener', subcommand=u'help', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:17 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:18 cli: CLI call info_name=u'pywbemlistener', subcommand=u'show', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:18 cli: CLI call info_name=u'pywbemlistener', subcommand=u'start', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:19 cli: CLI call info_name=u'pywbemlistener', subcommand=u'stop', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:19 cli: CLI call info_name=u'pywbemlistener', subcommand=u'test', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:20 cli: CLI call info_name=u'pywbemlistener', subcommand=u'run', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:20 cli: CLI call info_name=u'pywbemlistener', subcommand=u'docs', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:45 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:45 get_listeners: Enter get_listeners None\n',
u"2023-09-29 17:24:46 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:47 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:47 get_listeners: Enter get_listeners None\n',
u"2023-09-29 17:24:48 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:48 get_listeners: Enter get_listeners None\n',
u"2023-09-29 17:24:49 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u"2023-09-29 17:24:49 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:49 get_listeners: Enter get_listeners None\n',
u"2023-09-29 17:24:50 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:50 get_listeners: Enter get_listeners None\n',
u"2023-09-29 17:24:51 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:51 get_listeners: Enter get_listeners None\n',
u"2023-09-29 17:24:52 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:52 get_listeners: Enter get_listeners None\n',
u"2023-09-29 17:24:53 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:53 get_listeners: Enter get_listeners None\n',
u"2023-09-29 17:24:54 cli: CLI call info_name=u'pywbemlistener', subcommand=u'start', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'verbose': 2, 'logdir': None}\n",
u'2023-09-29 17:24:54 get_listeners: Enter get_listeners lis1\n',
u"2023-09-29 17:24:54 cli: CLI call info_name=u'pywbemlistener', subcommand=u'run', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'verbose': 2, 'logdir': None}\n",
u'2023-09-29 17:24:54 get_listeners: Enter get_listeners lis1\n',
u'2023-09-29 17:24:54 get_listeners: Found Listener: lis1 2023-09-29 17:24:53.950000\n',
u"2023-09-29 17:24:55 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:55 get_listeners: Enter get_listeners None\n',
u'2023-09-29 17:24:55 get_listeners: Found Listener: lis1 2023-09-29 17:24:53.950000\n',
u"2023-09-29 17:24:56 cli: CLI call info_name=u'pywbemlistener', subcommand=u'list', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': u'plain', 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:56 get_listeners: Enter get_listeners None\n',
u'2023-09-29 17:24:56 get_listeners: Found Listener: lis1 2023-09-29 17:24:53.950000\n',
u"2023-09-29 17:24:57 cli: CLI call info_name=u'pywbemlistener', subcommand=u'stop', command=<PywbemtoolsTopGroup cli>, params={'warn': False, 'output_format': None, 'pdb': False, 'logdir': None, 'verbose': 0}\n",
u'2023-09-29 17:24:57 cmd_listener_stop: cmd_listener_stop - enter lis1\n',
u'2023-09-29 17:24:57 get_listeners: Enter get_listeners lis1\n',
u'2023-09-29 17:24:57 get_listeners: Found Listener: lis1 2023-09-29 17:24:53.950000\n',
u'2023-09-29 17:24:57 cmd_listener_stop: cmd_listener_stop. before pusutil.Process 1298\n',
u'2023-09-29 17:24:57 cmd_listener_stop: cmd_listener_stop. before wait 1298\n']
===================== Fails by never return from the p.wait() as part of the listener stop command within the
                      pywbemlistener stop command during teardown
2023-09-29T17:25:26.5607450Z test teardown: Error: Stopping listener failed: Command 'pywbemlistener stop lis1' timed out after 30 seconds
2023-09-29T17:25:26.5607809Z Begin of command output (stdout):
2023-09-29T17:25:26.5608008Z None
2023-09-29T17:25:26.5608197Z End of command output
2023-09-29T17:25:26.5608431Z Begin of command output (stderr):
2023-09-29T17:25:26.5608621Z None
2023-09-29T17:25:26.5608808Z End of command output
2023-09-29T17:25:26.7486050Z [31mFAILED[0m
2023-09-29T17:25:26.7499335Z tests/unit/pywbemlistener/test_list_cmd.py::test_lis_list[Verify output of 'list' with two http listeners running-inputs4-exp_results4-verbose]
2023-09-29T17:25:26.7500181Z Executing testcase: Verify output of 'list' with two http listeners running
2023-09-29T17:25:26.7500638Z test setup: Listing listeners: pywbemlistener -o plain list
2023-09-29T17:25:26.7501032Z test setup: Command (shell): pywbemlistener -o plain list
2023-09-29T17:25:26.7529040Z Debug: test setup: Calling p.communicate
2023-09-29T17:25:27.5729031Z Debug: test setup: Returned from p.communicate() with 21 B on out, None B on stderr
2023-09-29T17:25:27.5729398Z Debug: test setup: Calling p.poll()
2023-09-29T17:25:27.5729677Z Debug: test setup: Returned from p.poll() with rc=0
2023-09-29T17:25:27.5730326Z test setup: Starting listener: pywbemlistener -vv start lis1 --scheme http --port 50001
2023-09-29T17:25:27.5730828Z test setup: Command (shell): pywbemlistener -vv start lis1 --scheme http --port 50001
2023-09-29T17:25:27.5756499Z Debug: test setup: Calling p.communicate
2023-09-29T17:25:29.1972786Z Debug: test setup: Returned from p.communicate() with 365 B on out, None B on stderr
2023-09-29T17:25:29.1973173Z Debug: test setup: Calling p.poll()
2023-09-29T17:25:29.1973472Z Debug: test setup: Returned from p.poll() with rc=0
2023-09-29T17:25:29.1974092Z test setup: Starting listener: pywbemlistener -vv start lis2 --scheme http --port 50002
2023-09-29T17:25:29.1974604Z test setup: Command (shell): pywbemlistener -vv start lis2 --scheme http --port 50002
2023-09-29T17:25:29.2007256Z Debug: test setup: Calling p.communicate
2023-09-29T17:25:29.9948332Z Traceback (most recent call last):
2023-09-29T17:25:29.9948691Z   File "/usr/local/bin/pywbemlistener", line 11, in <module>
2023-09-29T17:25:29.9949294Z     load_entry_point('pywbemtools', 'console_scripts', 'pywbemlistener')()
2023-09-29T17:25:29.9949700Z   File "/__w/pywbemtools/pywbemtools/pywbemtools/_click_extensions.py", line 134, in __call__
2023-09-29T17:25:29.9950018Z     return self.main(*args, **kwargs)
2023-09-29T17:25:29.9950441Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 782, in main
2023-09-29T17:25:29.9950729Z     rv = self.invoke(ctx)
2023-09-29T17:25:29.9951123Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
2023-09-29T17:25:29.9951465Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-09-29T17:25:29.9952223Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
2023-09-29T17:25:29.9952558Z     return ctx.invoke(self.callback, **ctx.params)
2023-09-29T17:25:29.9952968Z   File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
2023-09-29T17:25:29.9953262Z     return callback(*args, **kwargs)
2023-09-29T17:25:29.9953682Z   File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 33, in new_func
2023-09-29T17:25:29.9954014Z     return f(get_current_context().obj, *args, **kwargs)
2023-09-29T17:25:29.9954393Z   File "/__w/pywbemtools/pywbemtools/pywbemtools/pywbemlistener/_cmd_listener.py", line 401, in listener_start
2023-09-29T17:25:29.9954938Z     context.execute_cmd(lambda: cmd_listener_start(context, name, options))
2023-09-29T17:25:29.9955349Z   File "/__w/pywbemtools/pywbemtools/pywbemtools/pywbemlistener/_context_obj.py", line 171, in execute_cmd
2023-09-29T17:25:29.9955726Z     cmd()  # The command function for the pywbemlistener command
2023-09-29T17:25:29.9956120Z   File "/__w/pywbemtools/pywbemtools/pywbemtools/pywbemlistener/_cmd_listener.py", line 401, in <lambda>
2023-09-29T17:25:29.9956513Z     context.execute_cmd(lambda: cmd_listener_start(context, name, options))
2023-09-29T17:25:29.9956920Z   File "/__w/pywbemtools/pywbemtools/pywbemtools/pywbemlistener/_cmd_listener.py", line 1209, in cmd_listener_start
2023-09-29T17:25:29.9957250Z     listeners = get_listeners(name)
2023-09-29T17:25:29.9957597Z   File "/__w/pywbemtools/pywbemtools/pywbemtools/pywbemlistener/_cmd_listener.py", line 568, in get_listeners
2023-09-29T17:25:29.9957985Z     debug_log("Found Listener: {} {}".format(lis.name, lis.created))
2023-09-29T17:25:29.9958653Z UnboundLocalError: local variable 'lis' referenced before assignment
2023-09-29T17:25:30.0238430Z Debug: test setup: Returned from p.communicate() with None B on out, None B on stderr
2023-09-29T17:25:30.0238776Z Debug: test setup: Calling p.poll()
2023-09-29T17:25:30.0239063Z Debug: test setup: Returned from p.poll() with rc=1
2023-09-29T17:25:30.0239632Z test setup: Error: Starting listener failed: 'Popen' object has no attribute 'CalledProcessError'
2023-09-29T17:25:30.5466262Z [31mFAILED[0m

**Comment by andy-maier** [comment]
We have decided to give up on that and just not run this test on Python 2.7.
