### ISSUE TITLE
Not setting connection in interactive mode gives exception

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#231]
If pywbemcli is invoked in interactive mode, and the first command is anything that requires a connection but no connection is set, pywbemcli fails with exception traceback.

I would expect it to display an error message that a connection is needed, and to stay in interactive mode.

Exception raised (On MacOS, with Python 3.7.3), after typing `class enumerate<ENTER>`:

```
$ pywbemcli
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli.
pywbemcli> class enumerate                                                                                              
Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbem37/bin/pywbemcli", line 10, in <module>
    sys.exit(cli())
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/pywbemcli.py", line 387, in cli
    ctx.invoke(repl)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/pywbemcli.py", line 447, in repl
    click_repl.repl(ctx, prompt_kwargs=prompt_kwargs)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click_repl/__init__.py", line 248, in repl
    group.invoke(ctx)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbem37/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_class.py", line 186, in class_enumerate
    context.execute_cmd(lambda: cmd_class_enumerate(context, classname,
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 167, in execute_cmd
    cmd()
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_class.py", line 187, in <lambda>
    options))
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_class.py", line 394, in cmd_class_enumerate
    results = context.conn.EnumerateClasses(
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 105, in conn
    return self._pywbem_server.conn
AttributeError: 'NoneType' object has no attribute 'conn'
```

**Comment by andy-maier** [comment]
Fixed in PR #235.
