### ISSUE TITLE
Exceptions in mock Python script not handled well

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#292]
Exceptions raised in a Python script specified with `--mock-server` are not handled very nicely. For example, when using pywbem 0.14.4, using the new tst_file.py file from PR #291 results in pywbem raising a KeyError, which is presented as follows:
```
$ pywbemcli --mock-server tst_file.py class enumerate --names-only
Repository build exception CIMError.: 1 (CIM_ERR_FAILED): Exception failure of "--mock-server" python script u'/Users/maiera/PycharmProjects/pywbem/pywbemtools/tst_file.py' with conn FakedWBEMConnection(response_delay=None, super=WBEMConnection(url='http://FakedUrl', creds=None, conn_id='1-92435', default_namespace='root/cimv2', x509=None, verify_callback=None, ca_certs=None, no_verification=False, timeout=None, use_pull_operations='either', stats_enabled=False, recorders=[])) Exception: KeyError('0|A',)
Traceback
['Traceback (most recent call last):\n', '  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_pywbemcli_operations.py", line 320, in build_repository\n    exec(fp.read(), globalparams, None)\n', '  File "<string>", line 99, in <module>\n', '  File "<string>", line 88, in main\n', '  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pywbem_mock/_wbemconnection_mock.py", line 794, in add_cimobjects\n    self.add_cimobjects(obj, namespace=namespace)\n', '  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pywbem_mock/_wbemconnection_mock.py", line 814, in add_cimobjects\n    verbose=False)\n', '  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pywbem_mock/_resolvermixin.py", line 473, in _resolve_class\n    new_class, \'CLASS\')\n', '  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pywbem_mock/_resolvermixin.py", line 126, in _validate_qualifiers\n    (qname, new_class.classname, scope, q_decl.scopes)))\n', '  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/pywbem/_utils.py", line 287, in _format\n    return _ASCII2_FORMATTER.format(format_str, *args, **kwargs)\n', '  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 559, in format\n    return self.vformat(format_string, args, kwargs)\n', '  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 563, in vformat\n    result = self._vformat(format_string, args, kwargs, used_args, 2)\n', '  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 585, in _vformat\n    obj, arg_used = self.get_field(field_name, args, kwargs)\n', '  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 646, in get_field\n    obj = self.get_value(first, args, kwargs)\n', '  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 605, in get_value\n    return kwargs[key]\n', "KeyError: '0|A'\n"]
Aborted!
```

There are multiple issues with this:
- A KeyError is raised as a CIMError.
- The displaying of the repr() output of the connection object makes the exception text quite unreadable.
- The traceback is not shown as normally, but folded into a list, which makes it hard to read.

**Comment by andy-maier** [comment]
Issue #373 describes this better, so closing this one as a dup.
