### ISSUE TITLE
Display of traceback lines when handling error in mock Python scripts

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#373]
If a mock Python script encounters an exception that is not caught, that is considered a programming error, and the according the traceback is displayed by pywbemcli as additional information on an error message that says that the mock script had an error.

So far so good, but there are some issues with the way the error is displayed:
* Traceback lines are shown as a repr() formatted list of lines instead of the lines directly. That makes it hard to read.
* The error message already mentions the namespace in the text and then adds the repr() formatted target object, so that duplicates the namespace and also is a bit cumbersome to read.
* The error message says "localobject" which is not a defined term.
* The file path of the mock Python script is not in the error message. Normally, that would be in the traceback but for some reason the file is shown as "<string>".

BTW, I first thought I also needed to comment on the fact that a CIM error CIM_ERR_FAILED is used to report that, but when thinking about it, that is really what it should, because in a real server the corresponding situation would be an error in the server side implementation that the server would ideally report as a CIM error (as opposed to crashing), and CIM_ERR_FAILED is the only reasonable CIM status code for that. So that design was good thinking!

Example of current behavior with a connection `mockfuzzy` defined as `-m tests/unit/simple_mock_model.mof -m tests/unit/simple_mock_invokemethod.py`, and with an invalid line `x = y` in the method callback function:

```
$ pywbemcli -n mockfuzzy class invokemethod CIM_Foo Fuzzy
Error: CIMError: 1 (CIM_ERR_FAILED): Exception failure of invoked method 'Fuzzy' in namespace 'root/cimv2' with input localobject CIMClassName(classname='CIM_Foo', namespace='root/cimv2', host=None), parameters {}. Exception: global name 'y' is not defined
Traceback
['Traceback (most recent call last):\n', '  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_wbemconnection_mock.py", line 3471, in _fake_invokemethod\n    result = bound_method(self, methodname, localobject, , '  File "<string>", line 23, in fuzzy_callback\n', "NameError: global name 'y' is not defined\n"]
```

I think that should be changed to display the traceback lines directly, and I have also suggested some changes to the error message in the following:

```
$ pywbemcli -n mockfuzzy class invokemethod CIM_Foo Fuzzy
Error: CIMError: 1 (CIM_ERR_FAILED): Invocation of method 'Fuzzy' on class 'CIM_Foo' in namespace 'root/cimv2' failed due to exception in mock Python script tests/unit/simple_mock_invokemethod.py.
Traceback (most recent call last):
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_wbemconnection_mock.py", line 3471, in _fake_invokemethod
    result = bound_method(self, methodname, localobject, 
  File "<string>", line 23, in fuzzy_callback
  NameError: global name 'y' is not defined
```

**Comment by andy-maier** [comment]
Addressed with PR #391.
