### ISSUE TITLE
pywbemcli --version fails, "Could not determine version"

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#423]
pywbemcli  --version fails with python 2.7  "pywbemcli --version" with the following traceback but produces expected result with python 3 (see below)

```
$ pywbemcli --version
Traceback (most recent call last):
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/bin/pywbemcli", line 10, in <module>
    sys.exit(cli())
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/local/lib/python2.7/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/local/lib/python2.7/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/local/lib/python2.7/site-packages/click/core.py", line 1089, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/local/lib/python2.7/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/local/lib/python2.7/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/local/lib/python2.7/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/kschopmeyer/virtualenvs/pywbemtoolstmp/local/lib/python2.7/site-packages/click/decorators.py", line 270, in callback
    raise RuntimeError('Could not determine version')
RuntimeError: Could not determine version

```

Works fine with python 3

```
 pywbemcli  --version
pywbemcli, version 0.5.1.dev1
pywbem, version 0.14.5
(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools(ks/#419-mixed-formatter)$ python --version
Python 3.6.8

NOTE: Found this with test_general_options.py so it worked before the release.

**Comment by andy-maier** [comment]
In my Python 2.7 virtualenv, I get:
```
$ pywbemcli --version
pywbemcli, version 0.5.1.dev1
pywbem, version 0.14.6.dev1

$ python --version
Python 2.7.16

$ pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                            Version     Location                                        
---------------------------------- ----------- ------------------------------------------------
alabaster                          0.7.12      
appnope                            0.1.0       
asciitree                          0.3.3       
astroid                            1.6.6       
atomicwrites                       1.3.0       
attrs                              19.1.0      
Babel                              2.7.0       
backports-abc                      0.5         
backports.functools-lru-cache      1.5         
backports.shutil-get-terminal-size 1.0.0       
bleach                             3.1.0       
certifi                            2019.9.11   
chardet                            3.0.4       
Click                              7.0         
click-repl                         0.1.6       
click-spinner                      0.1.8       
configparser                       4.0.2       
contextlib2                        0.6.0       
coverage                           4.5.4       
decorator                          4.4.0       
defusedxml                         0.6.0       
docutils                           0.15.2      
dparse                             0.4.1       
entrypoints                        0.3         
enum34                             1.1.6       
filelock                           3.0.12      
flake8                             3.7.8       
funcsigs                           1.0.2       
functools32                        3.2.3.post2 
futures                            3.3.0       
gitdb2                             2.0.5       
GitPython                          2.1.14      
httpretty                          0.9.6       
idna                               2.8         
imagesize                          1.1.0       
importlib-metadata                 0.23        
ipaddress                          1.0.22      
ipykernel                          4.10.1      
ipython                            5.8.0       
ipython-genutils                   0.2.0       
ipywidgets                         7.5.1       
isort                              4.3.21      
Jinja2                             2.10.1      
jsonschema                         3.0.2       
jupyter                            1.0.0       
jupyter-client                     5.3.3       
jupyter-console                    5.2.0       
jupyter-core                       4.5.0       
lazy-object-proxy                  1.4.2       
linecache2                         1.0.0       
lxml                               4.3.5       
M2Crypto                           0.35.2      
MarkupSafe                         1.1.1       
mccabe                             0.6.1       
mistune                            0.8.4       
mock                               3.0.5       
more-itertools                     5.0.0       
nbconvert                          5.6.0       
nbformat                           4.4.0       
notebook                           5.7.8       
packaging                          19.2        
pandocfilters                      1.4.2       
pathlib2                           2.3.4       
pbr                                5.4.3       
pexpect                            4.7.0       
pickleshare                        0.7.5       
pip                                19.2.3      
pkginfo                            1.5.0.1     
pluggy                             0.13.0      
ply                                3.11        
prometheus-client                  0.7.1       
prompt-toolkit                     1.0.16      
ptyprocess                         0.6.0       
py                                 1.8.0       
pycodestyle                        2.5.0       
pyflakes                           2.1.1       
Pygments                           2.4.2       
pyinstrument                       3.0.3       
pyinstrument-cext                  0.2.2       
pylint                             1.9.5       
pyparsing                          2.4.2       
pyrsistent                         0.15.4      
pytest                             4.6.5       
pytest-cov                         2.5.1       
python-coveralls                   2.9.3       
python-dateutil                    2.8.0       
pytz                               2019.2      
pywbem                             0.14.6.dev1 /Users/maiera/PycharmProjects/pywbem/pywbem     
pywbemtools                        0.5.1.dev1  /Users/maiera/PycharmProjects/pywbem/pywbemtools
PyYAML                             5.1.2       
pyzmq                              18.1.0      
qtconsole                          4.5.5       
readme-renderer                    24.0        
requests                           2.22.0      
requests-toolbelt                  0.9.1       
safety                             1.8.5       
scandir                            1.10.0      
Send2Trash                         1.5.0       
setuptools                         41.2.0      
simplegeneric                      0.8.1       
singledispatch                     3.4.0.3     
six                                1.12.0      
smmap2                             2.0.5       
snowballstemmer                    1.9.1       
Sphinx                             1.8.5       
sphinx-git                         11.0.0      
sphinxcontrib-websupport           1.1.2       
tabulate                           0.8.5       
terminado                          0.8.2       
testfixtures                       5.4.0       
testpath                           0.4.2       
toml                               0.10.0      
tornado                            4.5.3       
tox                                3.14.0      
tqdm                               4.36.1      
traceback2                         1.4.0       
traitlets                          4.3.2       
twine                              1.15.0      
typing                             3.7.4.1     
unittest2                          1.1.0       
urllib3                            1.25.6      
virtualenv                         16.7.5      
wcwidth                            0.1.7       
webencodings                       0.5.1       
wheel                              0.33.6      
widgetsnbextension                 3.5.1       
wrapt                              1.11.2      
yamlordereddictloader              0.4.0       
zipp                               0.6.0       
```

The Python virtualenv was populated with pywbem `make develop` with its stable_0.14 branch, and pywbemtools `make develop` with its stable_0.5 branch.

**Comment by andy-maier** [comment]
The exception is raised here: https://github.com/pallets/click/blob/master/click/decorators.py#L270
and is caused by the pywbemcli script not being found by pkg_resources.

Can you check if `make install` on pywbemtools solves it?

**Comment by KSchopmeyer** [comment]
make install did not solve it.  However, creating a new virtual environment did.  However, I did not capture the list of imports before I rejuvinated the virtual envrionment causing the problem so not sure which were significantly different.  Needless to say, this was an OLD virtual environment for python 2 

**DISCUSSION** I propose we close this issue as cannot duplicate.
