### ISSUE TITLE
"make develop" fails when pywbem is not installed

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#488]
`make develop` fails as follows when the pywbem package is not installed in the active Python env:

```
$ make develop
rm -f install_py2.7.done
python -c "import pywbemtools.pywbemcli"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pywbemtools/pywbemcli/__init__.py", line 27, in <module>
    from ._cmd_class import *       # noqa: F403,F401
  File "pywbemtools/pywbemcli/_cmd_class.py", line 28, in <module>
    from pywbem import Error, CIMClassName, CIMError, CIM_ERR_NOT_FOUND, CIMClass
ImportError: No module named pywbem
make: *** [install_py2.7.done] Error 1
```

None of the make targets should have a hard dependency on pywbem being installed before having ensured that it is installed.

**Comment by andy-maier** [comment]
This issue seems to be a result of manually deleting some of the *.done files which is not supposed to be part of normal operations.

For example, this sequence does not run into the issue reported:
```
make develop   # to make sure all packages including pywbem are installed
make clobber
pip uninstall -y pywbem
make develop  # runs fine (reinstalls pywbem, the pywbemcli import check runs fine)
```

This sequence provokes the issue reported:
```
make develop   # to install all packages and create all *.done files
pip uninstall -y pywbem
rm install_py2.7.done   # to trigger the make rule that checks the pywbemcli import
make develop  # fails in the pywbemcli import check due to missing pywbem
```

The approach to recover from this situation is:
```
make clobber
make develop
```

The bottom line is: The approach with the *.done files can be undermined with manual actions on the *.done files. That is not supposed to be done however.

Closing this issue as not an issue.
