### ISSUE TITLE
yaml.RepresenterError when saving connections file

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#603]
pywbemcli raises yaml.RepresenterError when saving a connection to the connections file:

```
$ pywbemcli -m tests/unit/simple_assoc_mock_model.mof connection save assoc1
Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbem27/bin/pywbemcli", line 11, in <module>
    load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')()
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_connection.py", line 239, in connection_save
    context.execute_cmd(lambda: cmd_connection_save(context, name))
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 268, in execute_cmd
    cmd()
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_connection.py", line 239, in <lambda>
    context.execute_cmd(lambda: cmd_connection_save(context, name))
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_connection.py", line 585, in cmd_connection_save
    connections.add(save_connection.name, save_connection)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_connection_repository.py", line 195, in add
    self._write_file()
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_connection_repository.py", line 265, in _write_file
    indent=4)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/__init__.py", line 309, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/__init__.py", line 281, in dump_all
    dumper.represent(data)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 30, in represent
    node = self.represent_data(data)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 59, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 228, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 126, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 59, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 228, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 126, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 69, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/Users/maiera/virtualenvs/pywbem27/lib/python2.7/site-packages/yaml/representer.py", line 252, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', OrderedDict([(u'default-namespace', 'root/cimv2'), (u'user', None), (u'password', None), (u'ca-certs', None), (u'mock-server', ['tests/unit/simple_assoc_mock_model.mof']), (u'certfile', None), (u'name', 'assoc'), (u'verify', True), (u'server', None), (u'use_pull', None), (u'timeout', 30), (u'keyfile', None)]))
```

That happens both with and without a connections file (see below).

Listing connections works fine, both with and without a connections file.

Environment:
* Python: 2.7.16
* pywbemtools: master as of today
* OS: MacOS

connections file:
```
(pywbem27) Andreass-MacBook-Pro-2:pywbemtools maiera$ cat pywbemcli_connection_definitions.yaml
connection_definitions:
    assoc:
        default-namespace: root/cimv2
        user: null
        password: null
        ca-certs: null
        mock-server:
        - tests/unit/simple_assoc_mock_model.mof
        certfile: null
        name: assoc
        verify: true
        server: null
        use_pull: null
        timeout: 30
        keyfile: null
    assoc1:
        default-namespace: root/cimv2
        user: null
        password: null
        ca-certs: null
        mock-server:
        - tests/unit/simple_assoc_mock_model.mof
        certfile: null
        name: assoc1
        verify: true
        server: null
        use_pull: null
        timeout: 30
        keyfile: null
    assoc2:
        default-namespace: root/cimv2
        user: null
        password: null
        ca-certs: null
        mock-server:
        - tests/unit/complex_assoc_model.mof
        certfile: null
        name: assoc2
        verify: true
        server: null
        use_pull: null
        timeout: 30
        keyfile: null
default_connection_name: null
```

**Comment by andy-maier** [comment]
Fixed in PR #608 for master and TBD for 0.6.1
