### ISSUE TITLE
M2crypto install failure

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#69]
On Thursday, 5 October, M2crypto 0.27.0 was released.

Our travis started to fail immediately with the following::

Collecting pbr>=1.8 (from -r requirements.txt (line 6))
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting M2Crypto>=0.26.0 (from -r requirements.txt (line 7))
  Downloading M2Crypto-0.27.0.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 965kB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/M2Crypto.egg-info
    writing top-level names to pip-egg-info/M2Crypto.egg-info/top_level.txt
    writing requirements to pip-egg-info/M2Crypto.egg-info/requires.txt
    writing dependency_links to pip-egg-info/M2Crypto.egg-info/dependency_links.txt
    writing pip-egg-info/M2Crypto.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/M2Crypto.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g7w85pxk/M2Crypto/setup.py", line 350, in <module>
        'clean': Clean
      File "/opt/python/3.4.6/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/python/3.4.6/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/python/3.4.6/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 280, in run
        self.find_sources()
      File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 295, in find_sources
        mm.run()
      File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 526, in run
        self.add_defaults()
      File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/opt/python/3.4.6/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/opt/python/3.4.6/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-g7w85pxk/M2Crypto/setup.py", line 161, in finalize_options
        self.include_dirs += _get_additional_includes()
      File "/tmp/pip-build-g7w85pxk/M2Crypto/setup.py", line 51, in _get_additional_includes
        err = [line.lstrip() for line in err.split('\n') if line and line[0] == ' ']
    TypeError: 'str' does not support the buffer interface
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g7w85pxk/M2Crypto/

**Comment by KSchopmeyer** [comment]
Nailing the M2crypto version to 0.26.0 in requirements.txt bypasses this issue for the moment.
