### ISSUE TITLE
pywbemcli connection test --test-pull raises AssertionError

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#710]
The master branch and also the stable_0.7 branch of pywbemtools when using pywbem 1.0.0 raises AssertionError when `pywbemcli connection test --test-pull` is invoked. I verified that the error also happens when there is no connections file.

When pywbem 0.17.4 is used, the error does not happen. It seems to be related to better checking in the mock support of pywbem 1.0.0.

```
$ pywbemcli -m tests/unit/simple_mock_model.mof connection test --test-pull
Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 857, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 810, in main
    rv = self.invoke(ctx)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1292, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1292, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1099, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 613, in invoke
    return callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/decorators.py", line 31, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_connection.py", line 226, in connection_test
    context.execute_cmd(lambda: cmd_connection_test(context, options))
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 286, in execute_cmd
    cmd()
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_connection.py", line 226, in <lambda>
    context.execute_cmd(lambda: cmd_connection_test(context, options))
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_connection.py", line 621, in cmd_connection_test
    result = test_pull_operations(context, test_class)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_connection.py", line 482, in test_pull_operations
    result = cimcall(context.conn.OpenQueryInstances, "DMTF:CQL",
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_connection.py", line 446, in cimcall
    request(*pargs, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_operations.py", line 8198, in OpenQueryInstances
    result = self._imethodcall(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/mock/mock.py", line 1100, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/mock/mock.py", line 1104, in _mock_call
    return _mock_self._execute_mock_call(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/mock/mock.py", line 1167, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem_mock/_wbemconnection_mock.py", line 1071, in _mock_imethodcall
    result = methodnameattr(namespace, **params)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem_mock/_wbemconnection_mock.py", line 1695, in _imeth_OpenQueryInstances
    context_tuple = self._mainprovider.OpenQueryInstances(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem_mock/_mainprovider.py", line 3139, in OpenQueryInstances
    assert isinstance(ReturnQueryResultClass, (bool, type(None)))
AssertionError
```

**Comment by andy-maier** [comment]
The root cause is this error in pywbem, in pywbem_mock/_wbemconnection_mock.py:

```
    def _imeth_OpenQueryInstances(self, namespace, **params):
        """
        Call :meth:`~pywbem_mock.MainProvider.OpenQueryInstances` with
        parameters defined for that method and map response to tuple response
        for imethodcall.
        """
        context_tuple = self._mainprovider.OpenQueryInstances(
            namespace=namespace,
            FilterQueryLanguage=params.get('FilterQueryLanguage', None),
            FilterQuery=params.get('FilterQuery', None),
            ReturnQueryResultClass=params.get('FilterQueryLanguage', None),   # <-- incorrect parameter used
            OperationTimeout=params.get('OperationTimeout', None),
            ContinueOnError=params.get('ContinueOnError', None),
            MaxObjectCount=params.get('MaxObjectCount', None))
        return self._make_pull_imethod_resp(*context_tuple)
```
