### ISSUE TITLE
pywbemcli fails test with mock package 4.0.3.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#822]
When used with mock version 4.0.3, pywbemcli fails consistently in two different operating  modes:

1. pywbemcli < x.txt   # Entering commands with stdin.
2. interactive mode after a command has been executed (but it does not fail if the exit occurs before any command has been executed)

The following is an example of the failure with stdin but the failure itself is the same for both modes, a variable is not defined apparently because the mock __exit__ is executed without the corresponding  __enter__ being executed.

```
  pywbemcli < "class -h"

where the failure is in the exit mechanisms upon completing the stdin and the actuall error is:

```
    File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1529, in __exit__
      if self.is_local and self.temp_original is not DEFAULT:
   AttributeError: '_patch' object has no attribute 'is_local' 

The complete exception trace is:

```

(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools(ks/#817-class-tree-display-details)$ pywbemcli < x.txt
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
Usage: pywbemcli [GENERAL-OPTIONS] class COMMAND [ARGS] [COMMAND-OPTIONS]

  Command group for CIM classes.

  This command group defines commands to inspect classes, invoke methods on
  classes, delete classes.

  Creation and modification of classes is not currently supported.

  In addition to the command-specific options shown in this help text, the
  general options (see 'pywbemcli --help') can also be specified before the
  'class' keyword.

Command Options:
  -h, --help  Show this help message.

Commands:
  enumerate     List top classes or subclasses of a class in a namespace.
  get           Get a class.
  delete        Delete a class.
  invokemethod  Invoke a method on a class.
  references    List the classes referencing a class.
  associators   List the classes associated with a class.
  find          List the classes with matching class names on the server.
  tree          Show the subclass or superclass hierarchy for a class.
Traceback (most recent call last):
  File "/home/kschopmeyer/virtualenvs/pycli3/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1332, in decoration_helper
    yield (args, keywargs)
  File "/usr/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1529, in __exit__
    if self.is_local and self.temp_original is not DEFAULT:
AttributeError: '_patch' object has no attribute 'is_local'

**Comment by KSchopmeyer** [comment]
The error apprears to come from the update of the mock package from version 4.0.2 to 4.0.3 that occurred on 10 december but I have not determined if it is a click issue or a mock issue.

For the moment, the proposed fix is to restrict mock to < version 4.0.3.

**Comment by KSchopmeyer** [comment]
Another project had exactly  the same problem and fixed it by revamping the execution of multiple mock decorators.  See https://github.com/spulec/moto/pull/3541.

They had an exception in exactly the same place with the same issue as we are having as documented in issue https://github.com/spulec/moto/issues/3535

  File "../.venv/lib/python3.9/site-packages/mock/mock.py", line 1529, in __exit__
    if self.is_local and self.temp_original is not DEFAULT:

**Comment by KSchopmeyer** [comment]
The problem is in pywbemcli.py line 403 the statement:

```

@patch('warnings.formatwarning', formatwarning).

```

Removing that eliminates the failure and the complete test suite runs and this is consistent at superficially with the issue from moto package that was tied to multiple decorators that are executed multiple times.

**Comment by KSchopmeyer** [comment]
Note: We do not really test the interactive mode in the testsuite except for tests like the one that fails that use stdin to input multiple commands into a running environment since there is no way to actually execute multiple commands in an interactive pywbemcli shell except for stdin.  Therefore, it appears that the two cases (command with stdin and executing a command in interactive mode are effectively the same path.

The problem is that in this mode, the mock __exit__ is executed without the __enter__ being executed upon closing the interactive mode and since is_local is only set into the _patch class when __enter__ is executed, the variable is never set.  

So our next question is what is the sequence of events that causes the  mock._patch.__exit__ to be executed without a corresponding mock.patch.__enter__.

**Comment by KSchopmeyer** [comment]
Example where the class _patch __init__ __enter__, and __exit__ are instrumented to demonstrate the cases where is_local is created (__enter__) and destroyed (__exit__).  Note that it is actually deleted in __exit__ so that the second __exit__ does not find it.

=================== pywbemcli < x.txt  fails

NOTE: Does multiple enter on same patch object. and multiple exit. Since
      The exit removes is_local this fails
      
(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools(ks/test-mock-issue)$ pywbemcli < x.txt
mock._patch.__init__ self=<mock.mock._patch object at 0x7f1d706950f0>
mock._patch.__enter__ self-<mock.mock._patch object at 0x7f1d706950f0>
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
mock._patch.__enter__ self-<mock.mock._patch object at 0x7f1d706950f0>
mock._patch.__exit__ self<mock.mock._patch object at 0x7f1d706950f0>
Usage: pywbemcli [GENERAL-OPTIONS] class COMMAND [ARGS] [COMMAND-OPTIONS]

  Command group for CIM classes.

  This command group defines commands to inspect classes, invoke methods on
  classes, delete classes.

  Creation and modification of classes is not currently supported.

  In addition to the command-specific options shown in this help text, the
  general options (see 'pywbemcli --help') can also be specified before the
  'class' keyword.

Command Options:
  -h, --help  Show this help message.

Commands:
  enumerate     List top classes or subclasses of a class in a namespace.
  get           Get a class.
  delete        Delete a class.
  invokemethod  Invoke a method on a class.
  references    List the classes referencing a class.
  associators   List the classes associated with a class.
  find          List the classes with matching class names on the server.
  tree          Show the subclass or superclass hierarchy for a class.
mock._patch.__exit__ self<mock.mock._patch object at 0x7f1d706950f0>
Traceback (most recent call last):
  File "/home/kschopmeyer/virtualenvs/pycli3/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1348, in patched
    return func(*newargs, **newkeywargs)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1334, in decoration_helper
    yield (args, keywargs)
  File "/usr/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1537, in __exit__
    if self.is_local and self.temp_original is not DEFAULT:
AttributeError: '_patch' object has no attribute 'is_local'

=======================  pywbemcli to interactive mode and enter a command. Fails 
(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools(ks/test-mock-issue)$ pywbemcli
mock._patch.__init__ self=<mock.mock._patch object at 0x7f23aecfa908>
mock._patch.__enter__ self-<mock.mock._patch object at 0x7f23aecfa908>
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> class get PG_User
mock._patch.__enter__ self-<mock.mock._patch object at 0x7f23aecfa908>
mock._patch.__exit__ self<mock.mock._patch object at 0x7f23aecfa908>
Error: CIMError: 6 (CIM_ERR_NOT_FOUND): Class 'PG_User' not found in namespace 'root/cimv2'.
pywbemcli>                                                                      
mock._patch.__exit__ self<mock.mock._patch object at 0x7f23aecfa908>
Traceback (most recent call last):
  File "/home/kschopmeyer/virtualenvs/pycli3/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1348, in patched
    return func(*newargs, **newkeywargs)
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1334, in decoration_helper
    yield (args, keywargs)
  File "/usr/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/mock/mock.py", line 1537, in __exit__
    if self.is_local and self.temp_original is not DEFAULT:
AttributeError: '_patch' object has no attribute 'is_local'

================= Pywbemcli class get PG_User succeeds
(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools(ks/test-mock-issue)$ pywbemcli class get PG_User
mock._patch.__init__ self=<mock.mock._patch object at 0x7f2464af99b0>
mock._patch.__enter__ self-<mock.mock._patch object at 0x7f2464af99b0>
mock._patch.__exit__ self<mock.mock._patch object at 0x7f2464af99b0>
Error: CIMError: 6 (CIM_ERR_NOT_FOUND): Class 'PG_User' not found in namespace 'root/cimv2'.

**Comment by KSchopmeyer** [comment]
The issue is that __exit__ is issued multiple times and since is_local is deleted on the first __exit__ the next call fails.  It was in python 3.9 that the change was made to make the mock __entry__exit more rigid.  In earlier versions, the __exist__ had a test actually bypassed this issue.   Note that version 4.0.3 of mock is really just a copy of the unittest.mock that is in python 3.9.


PROPOSED SOLUTION

I still do not know what to do about this but the simplest solution seems to be to find another way to setup patch on warning than putting it in as a decorator on def cli.

**Comment by andy-maier** [comment]
PR #823 mitigates the issue by pinning mock to <4.0.3. A final solution is still needed.

**Comment by andy-maier** [comment]
We concluded we would continue using monkey patching of `warnings.formatwarning()`, which seems to be the recommended approach (see https://docs.python.org/3/library/warnings.html#module-warnings and https://stackoverflow.com/questions/2187269/print-only-the-message-on-warnings).

This means we need to change the approach on how the monkey patching is done so that we don't run into the issue again.

Independently, we may or may not open issues, but we don't depend on them:
- against Python unittest.mock for taking out the code that tolerates is_local not being there in exit
- against click-repl for invoking the context manager  recursively on the same object (requires a simple test case).

**Comment by andy-maier** [comment]
PR #839 provides the final fix for this issue.
