### ISSUE TITLE
Fix AttributeError: '_patch' object has no attribute 'is_local'

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#827]
This happens many times on Python 3.9, but not  on older Python versions.
See e.g. https://github.com/pywbem/pywbemtools/pull/825/checks?check_run_id=1624972515
```
      Traceback (most recent call last):
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/bin/pywbemcli", line 33, in <module>
E           sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/click/core.py", line 829, in __call__
E           return self.main(*args, **kwargs)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/click/core.py", line 782, in main
E           rv = self.invoke(ctx)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/click/core.py", line 1236, in invoke
E           return Command.invoke(self, ctx)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
E           return ctx.invoke(self.callback, **ctx.params)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/click/core.py", line 610, in invoke
E           return callback(*args, **kwargs)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
E           return f(get_current_context(), *args, **kwargs)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/mock/mock.py", line 1346, in patched
E           return func(*newargs, **newkeywargs)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/contextlib.py", line 124, in __exit__
E           next(self.gen)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/mock/mock.py", line 1332, in decoration_helper
E           yield (args, keywargs)
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/contextlib.py", line 513, in __exit__
E           raise exc_details[1]
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/contextlib.py", line 498, in __exit__
E           if cb(*exc_details):
E         File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/mock/mock.py", line 1529, in __exit__
E           if self.is_local and self.temp_original is not DEFAULT:
E       AttributeError: '_patch' object has no attribute 'is_local'
```

**Comment by andy-maier** [comment]
Duplicate of issue #822.
