### ISSUE TITLE
"instance count" command fails with OpenSSL error on pegasus container

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#916]
When performing an "instance count" command (and the default namespace) against the pegasus container, it fails with the traceback shown below, indicating "EOF occurred in violation of protocol" during SSL handshake.

Once that has happened, all subsequent pywbemcli commands error out with that same error, even commands that succeeded before. A stop/start of the pegasus container resets the condition. I have repeated this multiple times and it seems to be reproducible.

```
$ pywbemcli -n pegasus instance count
Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=5989): Max retries exceeded with url: /cimom (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_http.py", line 315, in wbem_request
    resp = conn.session.post(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=5989): Max retries exceeded with url: /cimom (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 605, in instance_count
    context.execute_cmd(lambda: cmd_instance_count(context, classname, options))
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 305, in execute_cmd
    cmd()  # The pywbemcli command function call.
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 605, in <lambda>
    context.execute_cmd(lambda: cmd_instance_count(context, classname, options))
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 1334, in cmd_instance_count
    inst_names = context.conn.EnumerateInstanceNames(cln, namespace=ns)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_operations.py", line 2833, in EnumerateInstanceNames
    result = self._imethodcall(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_operations.py", line 1836, in _imethodcall
    reply_data, self._last_server_response_time = wbem_request(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_http.py", line 320, in wbem_request
    raise ConnectionError(msg, conn_id=conn.conn_id)
pywbem._exceptions.ConnectionError: EOF occurred in violation of protocol (_ssl.c:1125); OpenSSL version used: OpenSSL 1.1.1i  8 Dec 2020
```
The 'pegasus' connection looks like this:
```
$ pywbemcli connection show pegasus
Connection status:
name               value  (state)
-----------------  ----------------------
name               pegasus
server             https://localhost:5989
default-namespace  root/cimv2
user
password
timeout            60
use-pull
pull-max-cnt       1000
verify             False
certfile
keyfile
mock-server
ca-certs
```
The WBEM server behind that connection is the pegasus container, created with:
```
$ docker create --name pegasus -p 5988:5988 -p 5989:5989 keyporttech/smi-server:0.1.2
```
The versions of pywbemtools and pywbem are the respective master branches as of now, and the set of Python packages is:
```
$ pip list
Package                       Version    Location
----------------------------- ---------- ------------------------------------------------
alabaster                     0.7.12
appdirs                       1.4.4
asciitree                     0.3.3
astroid                       2.5.1
attrs                         20.3.0
Babel                         2.9.0
bleach                        3.3.0
certifi                       2020.12.5
chardet                       4.0.0
click                         7.1.2
click-repl                    0.1.6
click-spinner                 0.1.10
colorama                      0.4.4
coverage                      5.5
coveralls                     2.2.0
distlib                       0.3.1
docopt                        0.6.2
docutils                      0.16
dparse                        0.5.1
entrypoints                   0.3
filelock                      3.0.12
flake8                        3.8.4
gitdb                         4.0.5
GitPython                     3.1.14
idna                          2.10
imagesize                     1.2.0
iniconfig                     1.1.1
isort                         5.7.0
Jinja2                        2.11.3
keyring                       22.3.0
lazy-object-proxy             1.5.2
MarkupSafe                    1.1.1
mccabe                        0.6.1
mock                          4.0.3
nocasedict                    1.0.2
nocaselist                    1.0.4
packaging                     20.9
pip                           21.0.1
pkginfo                       1.7.0
pluggy                        0.13.1
ply                           3.11
prompt-toolkit                3.0.16
py                            1.10.0
pycodestyle                   2.6.0
pyflakes                      2.2.0
Pygments                      2.8.0
pylint                        2.7.2
pyparsing                     2.4.7
pytest                        6.2.2
pytest-cov                    2.11.1
pytz                          2021.1
pywbem                        1.2.0.dev1
pywbemtools                   0.9.0.dev1 /Users/maiera/PycharmProjects/pywbem/pywbemtools
PyYAML                        5.4.1
readme-renderer               29.0
requests                      2.25.1
requests-toolbelt             0.9.1
rfc3986                       1.4.0
safety                        1.10.3
setuptools                    54.0.0
six                           1.15.0
smmap                         3.0.5
snowballstemmer               2.1.0
Sphinx                        3.5.1
sphinx-git                    11.0.0
sphinx-rtd-theme              0.5.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-fulltoc         1.2.0
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
tabulate                      0.8.9
toml                          0.10.2
toposort                      1.6
tqdm                          4.58.0
twine                         3.3.0
urllib3                       1.26.3
virtualenv                    20.4.2
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.36.2
wrapt                         1.12.1
yamlloader                    0.5.5
```

**Comment by andy-maier** [comment]
I have captured a pywbemcli http log (attached).

The sequence of operations that the "instance count" operation performs until it fails, is:
```
CIMMethod:'EnumerateInstanceNames' CIMObject:'interop'
CIMMethod:'EnumerateInstanceNames' CIMObject:'root/interop'
CIMMethod:'EnumerateInstances' CIMObject:'root/interop'
CIMMethod:'EnumerateClassNames' CIMObject:'root'
CIMMethod:'EnumerateClassNames' CIMObject:'root/PG_Internal'
CIMMethod:'EnumerateClassNames' CIMObject:'root/SampleProvider'
CIMMethod:'EnumerateClassNames' CIMObject:'root/benchmark'
CIMMethod:'EnumerateClassNames' CIMObject:'root/cimv2'
CIMMethod:'EnumerateClassNames' CIMObject:'root/interop'
CIMMethod:'EnumerateClassNames' CIMObject:'test/CimsubTestNS0'
CIMMethod:'EnumerateClassNames' CIMObject:'test/CimsubTestNS1'
CIMMethod:'EnumerateClassNames' CIMObject:'test/CimsubTestNS2'
CIMMethod:'EnumerateClassNames' CIMObject:'test/CimsubTestNS3'
CIMMethod:'EnumerateClassNames' CIMObject:'test/EmbeddedInstance/Dynamic'
CIMMethod:'EnumerateClassNames' CIMObject:'test/EmbeddedInstance/Static'
CIMMethod:'EnumerateClassNames' CIMObject:'test/TestINdSrcNS2'
CIMMethod:'EnumerateClassNames' CIMObject:'test/TestIndSrcNS1'
CIMMethod:'EnumerateClassNames' CIMObject:'test/TestProvider'
CIMMethod:'EnumerateClassNames' CIMObject:'test/cimv2'
CIMMethod:'EnumerateClassNames' CIMObject:'test/static'
CIMMethod:'EnumerateInstanceNames' CIMObject:'root/PG_Internal' # fails
```

It fails when enumerating instance names of class 'PG_Authorization' in the 'root/PG_Internal' namespace.

That can also be reproduced when just enumerating the instance names of that class.

Here is a complete sequence of the behavior:
```
$ docker restart pegasus
pegasus

$ pywbemcli -n pegasus server info
Server General Information
Brand        Version    Interop Namespace    Namespaces
-----------  ---------  -------------------  -----------------------------
OpenPegasus  2.14.2     root/interop         root
                                             root/PG_Internal
                                             root/SampleProvider
                                             root/benchmark
                                             root/cimv2
                                             root/interop
                                             test/CimsubTestNS0
                                             test/CimsubTestNS1
                                             test/CimsubTestNS2
                                             test/CimsubTestNS3
                                             test/EmbeddedInstance/Dynamic
                                             test/EmbeddedInstance/Static
                                             test/TestINdSrcNS2
                                             test/TestIndSrcNS1
                                             test/TestProvider
                                             test/cimv2
                                             test/static

$ pywbemcli -n pegasus instance enumerate PG_Authorization -n root/PG_Internal
Error: ConnectionError: EOF occurred in violation of protocol (_ssl.c:1125); OpenSSL version used: OpenSSL 1.1.1i  8 Dec 2020

$ pywbemcli -n pegasus server info
Error: ConnectionError: EOF occurred in violation of protocol (_ssl.c:1125); OpenSSL version used: OpenSSL 1.1.1i  8 Dec 2020

$ docker restart pegasus
pegasus

$ pywbemcli -n pegasus server info
Server General Information
Brand        Version    Interop Namespace    Namespaces
-----------  ---------  -------------------  -----------------------------
OpenPegasus  2.14.2     root/interop         root
                                             root/PG_Internal
                                             root/SampleProvider
                                             root/benchmark
                                             root/cimv2
                                             root/interop
                                             test/CimsubTestNS0
                                             test/CimsubTestNS1
                                             test/CimsubTestNS2
                                             test/CimsubTestNS3
                                             test/EmbeddedInstance/Dynamic
                                             test/EmbeddedInstance/Static
                                             test/TestINdSrcNS2
                                             test/TestIndSrcNS1
                                             test/TestProvider
                                             test/cimv2
                                             test/static
```

**Comment by andy-maier** [comment]
We agreed this should be fixed in OpenPegasus. Please post the OpenPegasus issue to have the crosslink.

**DISCUSSION:** Should we also check for this in pywbemtools, to not run into it with older Pegasus versions?

**Comment by KSchopmeyer** [comment]
See github issue PG_Authorization

https://github.com/OpenPegasus/OpenPegasus/issues/49

Note that just doing instance enumerate on at least PG_User causes the failure.

**Comment by KSchopmeyer** [comment]
We will leave this open until the OpenPegasus issue is solved.

**Comment by andy-maier** [comment]
Options for pywbemtools:
1. Do nothing and rely on OpenPegasus fixing it. The "instance count" command will not work with unfixed OpenPegasus versions when HTTPS is used.
2. Add a namespace exclusion option to the "instance count" command.
3. Have an internal namespace exclusion list for the "instance count" command.

**Comment by andy-maier** [comment]
The plan for this issue is to wait for a pegasus container that has the fix, before we add a testcase with "instance count". Moved the issue to next release.

**Comment by KSchopmeyer** [comment]
I propose that:

1. Fix issue so that CIMError only affects the current enumerateinstance but that the scan of classes for instances continues.
2. Error Exception causes the scan to stop because this normally represents a fatal error to the server.  However, all remaining classes to be scanned will be listed with a status "not scanned" in place of the count.
3. An option be added to allow the scan to ignore defined classes.  This would be "--ignore-class" where it is a multiple input option and the list of classes can be either multiple uses of the option with a single classname  or a comma-separated list of class names.

**Comment by KSchopmeyer** [comment]
Note that we further reduced the list of instance enumerate cases where OpenPegasus fails to some classes in the PG_Internal namespace including: PG_Authorization, and PG_User.  Both of these kill OpenPegasus today.

In addition, some other classes result in CIMError including PG_Shutdown.

It boggles my mind that we make these classes publically available but have never provide means to block them from the user, in particular since they were really mostly containers for OpenPegaus action (ex. shutdown) and not real classes.
