### ISSUE TITLE
Issues with "?" as namespace name

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#963]
The following command crashes with COnnectionError. There are two issues with it:
1. pywbemcli should not show the traceback but a proper error message
2. This is using the OpenPegasus container, which should respond with an namespace not found error instead of connection error.

```
$ pywbemcli -n pegasus instance get -n "?" "CIM_ManagedSystemElement.?"
Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='localhost', port=5989): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_http.py", line 315, in wbem_request
    resp = conn.session.post(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/requests/models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=5989): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools38/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 262, in instance_get
    context.execute_cmd(lambda: cmd_instance_get(context, instancename,
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 347, in execute_cmd
    cmd()  # The pywbemcli command function call.
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 262, in <lambda>
    context.execute_cmd(lambda: cmd_instance_get(context, instancename,
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 980, in cmd_instance_get
    instancepath = get_instancename(context, instancename, options)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 870, in get_instancename
    instance_path = pick_instance(
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_common.py", line 359, in pick_instance
    instance_names = conn.PyWbemcliEnumerateInstancePaths(objectname,
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_pywbemcli_operations.py", line 93, in PyWbemcliEnumerateInstancePaths
    return list(result)
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_operations.py", line 4973, in IterEnumerateInstancePaths
    pull_result = self.OpenEnumerateInstancePaths(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_operations.py", line 6982, in OpenEnumerateInstancePaths
    result = self._imethodcall(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_operations.py", line 1823, in _imethodcall
    reply_data, self._last_server_response_time = wbem_request(
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/pywbem/_cim_http.py", line 323, in wbem_request
    raise ConnectionError(msg, conn_id=conn.conn_id)
pywbem._exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=5989): Read timed out.; OpenSSL version used: OpenSSL 1.1.1i  8 Dec 2020
```

**Comment by andy-maier** [comment]
I confirmed that with the current code, the originally posted command still fails i the same way.

Running this against a mocked environment results in a different error:
```
(pywbemtools39) Andreass-MBP-2:pywbemtools maiera$ pywbemcli -n simple_interop instance get -n "?" "CIM_ManagedSystemElement.?"
Traceback (most recent call last):
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_inmemoryrepository.py", line 248, in validate_namespace
    self._repository[namespace]
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/_nocasedict.py", line 81, in __getitem__
    return super(NocaseDict, self).__getitem__(key)
  File "/Users/maiera/virtualenvs/pywbemtools39/lib/python3.9/site-packages/nocasedict/_nocasedict.py", line 304, in __getitem__
    raise key_error  # pylint: disable=raise-missing-from
KeyError: "Key '?' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_baseprovider.py", line 149, in validate_namespace
    self.cimrepository.validate_namespace(namespace)
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_inmemoryrepository.py", line 250, in validate_namespace
    raise KeyError('Namespace "{}" does not exist in repository'.
KeyError: 'Namespace "?" does not exist in repository'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maiera/virtualenvs/pywbemtools39/bin/pywbemcli", line 33, in <module>
    sys.exit(load_entry_point('pywbemtools', 'console_scripts', 'pywbemcli')())
  File "/Users/maiera/virtualenvs/pywbemtools39/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools39/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/maiera/virtualenvs/pywbemtools39/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbemtools39/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/maiera/virtualenvs/pywbemtools39/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/maiera/virtualenvs/pywbemtools39/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/maiera/virtualenvs/pywbemtools39/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 263, in instance_get
    context.execute_cmd(lambda: cmd_instance_get(context, instancename,
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_context_obj.py", line 347, in execute_cmd
    cmd()  # The pywbemcli command function call.
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 263, in <lambda>
    context.execute_cmd(lambda: cmd_instance_get(context, instancename,
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 970, in cmd_instance_get
    instancepath = get_instancename(context, instancename, options)
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_cmd_instance.py", line 860, in get_instancename
    instance_path = pick_instance(
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_common.py", line 183, in pick_instance
    instance_names = conn.PyWbemcliEnumerateInstancePaths(objectname,
  File "/Users/maiera/PycharmProjects/pywbem/pywbemtools/pywbemtools/pywbemcli/_pywbemcli_operations.py", line 93, in PyWbemcliEnumerateInstancePaths
    return list(result)
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/_cim_operations.py", line 5176, in IterEnumerateInstancePaths
    pull_result = self.OpenEnumerateInstancePaths(
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/_cim_operations.py", line 7237, in OpenEnumerateInstancePaths
    result = self._imethodcall(
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/mock.py", line 1093, in __call__
    return self._mock_call(*args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/mock.py", line 1097, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/mock.py", line 1158, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_wbemconnection_mock.py", line 1188, in _mock_imethodcall
    result = methodnameattr(namespace, **params)
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_wbemconnection_mock.py", line 1711, in _imeth_OpenEnumerateInstancePaths
    context_tuple = self._mainprovider.OpenEnumerateInstancePaths(
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_mainprovider.py", line 2893, in OpenEnumerateInstancePaths
    self.validate_namespace(namespace)
  File "/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem_mock/_baseprovider.py", line 151, in validate_namespace
    raise CIMError(
pywbem._exceptions.CIMError: 3 (CIM_ERR_INVALID_NAMESPACE): Namespace does not exist in CIM repository: '?'
```

**Comment by andy-maier** [comment]
The root of the problem was that in `pick_instance()`, thecandidate instances were enumerated without catching any errors.

PR XXX fixes that by catching `pywbem.Error` exceptions and ending the command, consistent with other places in the code.

This changed the behavior of the two failing commands posted above as follows:
```
$ pywbemcli -n pegasus instance get -n "?" "CIM_ManagedSystemElement.?"
Error: ConnectionError: HTTPSConnectionPool(host='localhost', port=5989): Read timed out.; OpenSSL version used: OpenSSL 1.1.1i  8 Dec 2020

$ pywbemcli -n simple_interop instance get -n "?" "CIM_ManagedSystemElement.?"
Error: CIMError: 3 (CIM_ERR_INVALID_NAMESPACE): Namespace does not exist in CIM repository: '?'
```

**Comment by andy-maier** [comment]
I did some further analysis on the read timeout with the pegasus container.

The following command shows that the request message for OpenEnumerateInstancePaths is sent to pegasus, but a response message is not received within the timeout period. The timeout of the connection is 60 s, and it is using https without cert verification:
```
$ pywbemcli --log http=stderr -n pegasus instance get -n "?" "CIM_ManagedSystemElement.?"
-2021-07-19 08:46:36,676-pywbem.http.1-43929-Connection:1-43929 WBEMConnection(url='https://localhost:5989', creds=None, conn_id='1-43929', default_namespace='root/cimv2', x509=None, ca_certs=None, no_verification=True, timeout=60, use_pull_operations=None, stats_enabled=True, recorders=['LogOperationRecorder'])
2021-07-19 08:46:36,676-pywbem.http.1-43929-Request:1-43929 POST /cimom 11 https://localhost:5989 CIMOperation:'MethodCall' CIMMethod:'OpenEnumerateInstancePaths' CIMObject:'?' '<?xml version="1.0" encoding="utf-8" ?>\n<CIM CIMVERSION="2.0" DTDVERSION="2.0"><MESSAGE ID="1001" PROTOCOLVERSION="1.0"><SIMPLEREQ><IMETHODCALL NAME="OpenEnumerateInstancePaths"><LOCALNAMESPACEPATH><NAMESPACE NAME="?"/></LOCALNAMESPACEPATH><IPARAMVALUE NAME="ClassName"><CLASSNAME NAME="CIM_ManagedSystemElement"/></IPARAMVALUE><IPARAMVALUE NAME="MaxObjectCount"><VALUE>1000</VALUE></IPARAMVALUE></IMETHODCALL></SIMPLEREQ></MESSAGE></CIM>'
Error: ConnectionError: HTTPSConnectionPool(host='localhost', port=5989): Read timed out.; OpenSSL version used: OpenSSL 1.1.1i  8 Dec 2020
```

A comparison command using an equally non-existing namespace but with a valid format results in immediate return of the namespace not found error, as it should:
```
$ pywbemcli -n pegasus instance get -n "bad/ns" "CIM_ManagedSystemElement.?"
Error: CIMError: 3 (CIM_ERR_INVALID_NAMESPACE): CIM_ERR_INVALID_NAMESPACE: bad/ns
```

**Comment by andy-maier** [comment]
While trying out different commands in context of this issue, I encountered a second issue in pegasus:

```
$ pywbemcli -n pegasus instance get "CIM_ManagedSystemElement.?"
Pick Instance name to process
0: //5d9861aca14e/root/cimv2:PG_ComputerSystem.CreationClassName="PG_ComputerSystem",Name="5d9861aca14e"
1: //5d9861aca14e/root/cimv2:PG_OperatingSystem.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="CIM_OperatingSystem",Name="Debian GNU/Linux Distribution"
2: //5d9861aca14e/root/cimv2:PG_UnixProcess.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="PG_UnixProcess",Handle="1",OSCreationClassName="CIM_OperatingSystem",OSName="Debian GNU/Linux Distribution"
3: //5d9861aca14e/root/cimv2:PG_UnixProcess.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="PG_UnixProcess",Handle="11",OSCreationClassName="CIM_OperatingSystem",OSName="Debian GNU/Linux Distribution"
4: //5d9861aca14e/root/cimv2:PG_UnixProcess.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="PG_UnixProcess",Handle="16",OSCreationClassName="CIM_OperatingSystem",OSName="Debian GNU/Linux Distribution"
5: //5d9861aca14e/root/cimv2:PG_UnixProcess.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="PG_UnixProcess",Handle="39",OSCreationClassName="CIM_OperatingSystem",OSName="Debian GNU/Linux Distribution"
6: //5d9861aca14e/root/cimv2:PG_UnixProcess.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="PG_UnixProcess",Handle="43",OSCreationClassName="CIM_OperatingSystem",OSName="Debian GNU/Linux Distribution"
7: //5d9861aca14e/root/cimv2:PG_UnixProcess.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="PG_UnixProcess",Handle="48",OSCreationClassName="CIM_OperatingSystem",OSName="Debian GNU/Linux Distribution"
8: //5d9861aca14e/root/cimv2:PG_UnixProcess.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="PG_UnixProcess",Handle="53",OSCreationClassName="CIM_OperatingSystem",OSName="Debian GNU/Linux Distribution"
9: //5d9861aca14e/root/cimv2:PG_UnixProcess.CSCreationClassName="CIM_UnitaryComputerSystem",CSName="5d9861aca14e",CreationClassName="PG_UnixProcess",Handle="54",OSCreationClassName="CIM_OperatingSystem",OSName="Debian GNU/Linux Distribution"
Input integer between 0 and 9 or Ctrl-C to exit selection: 9
Error: CIMError: 6 (CIM_ERR_NOT_FOUND): CIM_ERR_NOT_FOUND: 54: No such process
```
This error was not reproducable, I tried this command several times.

When the error happened, this was immediately after I Ctrl-C'ed a pywbemcli command that triggered the read timeout (see above). I tried to combine these two as well in my attempts to reproduce it, with no luck.

From the reproduction attempts that succeeded, I could see that item 9 was consistently the process `/root/smi/home/bin/cimprovagt`.
